### ISSUE TITLE
Buttons that link to external sites should include external icon

### ISSUE THREAD

**Issue by barrymcgee** [ubuntudesign/vanilla-framework#358]
## Context
Buttons that link to external sites should include an icon within the button boundaries after the text to indicate to the user they are to be taken to a different site.

## Related ticket
https://github.com/ubuntudesign/www.ubuntu.com/issues/639

**Comment by anthonydillon** [comment]
The way we do that at the moment is to wrap the link text in a span with an
external class. This is because on a button that is display block or mobile
buttons which are 100% width. We want the icon on the next to the text not
aligned to the right on the button itself.

Hope that make sense. If not let me know.
