### ISSUE TITLE
Investigate alternative font inclusion

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#462]
## Context

There are cases where we need to use the framework completely locally. Therefore the fonts need to be pulled locally or we alternatively provide a different way of including fonts, if they want them.

## Actions

Spike the following two options for off-site sprint:

- [ ] Drop vanilla opinions on fonts and use system approach and provide google fonts snippet
- [ ] Base64 and inline Ubuntu fonts into Vanilla
- [ ] Compare results and report back on file size considerations

**Comment by barrymcgee** [comment]
Agreed: we should base64 small icons / images

Spike the following two options for off-site sprint:

1. Drop vanilla opinions on fonts and use system approach and provide google fonts snippet
2. Base64 Ubuntu fonts into Vanilla

Compare and report back.

**Comment by WillMoggridge** [comment]
Including base64 versions of fonts resulted in a 300+KB increase in size, when the Ubuntu stylesheet is already at 600KB.

This would be extra overhead everytime the stylesheet changes. If we are able to use Google Fonts, it would take advantage of centralised caching of fonts.
Otherwise, I made the PR to fallback to the best system font available.
