### ISSUE TITLE
Inline-images pattern displays images at their natural size

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/vanilla-framework#724]
## Is this a proposal or an amendment?

- Amendment

Inline-images

## Visual

Current:
![ubuntu in the cloud cloud ubuntu](https://cloud.githubusercontent.com/assets/1413534/21311588/d39f2f70-c5df-11e6-9c6f-b4f4b74ef464.png)

Desired:
![ubuntu in the cloud cloud ubuntu](https://cloud.githubusercontent.com/assets/1413534/21311611/f2c8c56e-c5df-11e6-8e82-56a6d1cb3fff.png)

## Context

The inline-images pattern does not limit the size of the logos. It should size them to fit nicely together.

**Comment by barrymcgee** [comment]
This is a feature, not a bug. The reason is that I didn't think we should be allowing for people to add huge images that we then correct visually via CSS but still allow huge file sizes to remain.

If you add the images all equal size, they will display as desired above.

I think the action here is not to change any code but add a note to explicitly change this in the docs.

**Comment by yaili** [comment]
This is not a feature. This is a bug.

**Comment by barrymcgee** [comment]
@yaili Explanations are preferable to declarations please - why is this a bug and why should we allow users to mask huge file sizes?

**Comment by yaili** [comment]
Ant's original comment explains why this is a bug. It's not implemented as it was originally defined. The decision to change to behave differently wasn't discussed or agreed. The pattern is not only used with images created by the web team, it should constrain the image size.

**Comment by anthonydillon** [comment]
We should be promoting the use of SVGs. In that case the SVGs would need to have the right viewbox attribute. This makes them harder to reuse the image in different situations.
